org: bculbersonsf
app: snowflake-python-api
service: snowflake-python-api

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: us-west-2

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - '!__pycache__/**'
    - '!_node_modules/**'
    - '!venv/**'

